services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${POSTGRES_LOCAL_PATH}:/temp
      - ${SCRIPTS_PATH}:/scripts

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PGADMIN_CONTAINER_NAME}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_EXTERNAL_PORT}:${PGADMIN_INTERNAL_PORT}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ${SCRIPTS_PATH}:/var/lib/pgadmin/storage/${PGADMIN_DEFAULT_EMAIL}/scripts
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: